# syntax=docker/dockerfile:1

# This builds a MMSgate image from the flexisip installed and pjsip installed images
FROM pjsip

MAINTAINER https://github.com/RVgo4it

# install needed apps
USER root
RUN apt install -y python3-suds dumb-init

# Configure user mmsgate, no sudo
RUN useradd -ms /bin/bash mmsgate && \
    echo 'mmsgate:notnot' | chpasswd

# user the mmsgate script runs as
USER mmsgate
WORKDIR /home/mmsgate

# data and mmsmedia will be volumes at run time
RUN mkdir ~/script && \
	mkdir ~/data && \
	mkdir ~/mmsmedia

# Copy over the scripts
COPY --chown=mmsgate mmsgate/mmsgate.py script
COPY --chown=mmsgate mmsgate/makexmlconf.py script
COPY --chown=mmsgate mmsgate/mmsreconcile.py script
RUN	chmod +x script/*

# Default user for the container
USER bc
WORKDIR /home/bc

# Generate the default config file
RUN sudo /home/mmsgate/script/mmsgate.py --default-config | sudo tee /etc/flexisip/mmsgate.conf

# Copy over the initial script that starts the other programs
COPY --chown=bc mmsgate/init.sh .
RUN	chmod +x init.sh

# TZ will match the host
VOLUME	/etc/timezone:/etc/timezone:ro /etc/localtime:/etc/localtime:ro

# Startup config
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/home/bc/init.sh"]
